name: Build Windows EXE (PyInstaller)

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches: [ "release", "main", "new" ]
    tags:
    - 'v*'
  pull_request:
    branches: [ "release", "main", "new" ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller pillow

    - name: Generate all icons
      run: |
        python build_assets/universal_icon_generator.py

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --noconfirm --onefile --console --name StudentScoresApp `
         --collect-all streamlit `
         --copy-metadata streamlit `
         --add-data "webapp;webapp" `
         --add-data "config;config" `
         --add-data "hooks;hooks" `
         --add-data "build_assets;build_assets" `
         --icon build_assets/icon.ico `
         --additional-hooks-dir=./hooks `
         --clean `
         entrypoint.py

    - name: Archive artifacts
      run: |
        $out = Join-Path $env:GITHUB_WORKSPACE 'upload'
        New-Item -ItemType Directory -Path $out -Force | Out-Null
        Copy-Item dist/StudentScoresApp.exe $out/
        if (Test-Path config) { Copy-Item config $out/ -Recurse -Force }
        if (Test-Path webapp/student_scores.db) { Copy-Item webapp/student_scores.db $out/ }

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: StudentScoresApp-windows
        path: upload/*
        if-no-files-found: error

    - name: Create GitHub Release (for tags)
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          upload/StudentScoresApp.exe
          upload/config/**
          upload/student_scores.db
