name: Build Windows EXE (PyInstaller)

on:
  workflow_dispatch:
  push:
    branches:
    - release
    paths:
    - 'ma/streamlit_version/**'
    tags:
    - 'v*'
  pull_request:
    branches:
    - release
    paths:
    - 'ma/streamlit_version/**'

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        cd ma\streamlit_version
        python -m pip install --upgrade pip
        if (Test-Path requirements_streamlit.txt) {
          pip install -r requirements_streamlit.txt
        } else {
          pip install streamlit pandas plotly openpyxl numpy pathlib
        }
        pip install pyinstaller pillow

    - name: Generate icon
      run: |
        cd ma\streamlit_version
        python build_assets/make_icon.py

    - name: Verify launcher exists
      run: |
        cd ma\streamlit_version
        if (!(Test-Path run_app.py)) { echo "run_app.py not found"; exit 1 }

    - name: Build EXE with PyInstaller
      run: |
        cd ma\streamlit_version
        pyinstaller --noconfirm ^
          --onefile ^
          --name StudentScoresApp ^
          --collect-all streamlit ^
          --add-data "app.py;." ^
          --add-data "analyzer.py;." ^
          --add-data "database.py;." ^
          --add-data "styles.py;." ^
          --add-data "config.py;." ^
          --add-data "config;config" ^
          --add-data "pages;pages" ^
          --icon icon.ico ^
          --hidden-import pandas ^
          --hidden-import numpy ^
          --hidden-import plotly ^
          --hidden-import openpyxl ^
          run_app.py

    - name: Archive artifacts
      run: |
        cd ma\streamlit_version
        New-Item -ItemType Directory -Path upload -Force | Out-Null
        Copy-Item dist/StudentScoresApp.exe upload/
        if (Test-Path dist-extra) { Copy-Item dist-extra/* upload/ -Recurse }

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: StudentScoresApp-windows
        path: ma/streamlit_version/upload/*
        if-no-files-found: error

    - name: Create GitHub Release (for tags)
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ma/streamlit_version/upload/StudentScoresApp.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
