name: Build Streamlit App (Windows)

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    # 手动触发

jobs:
  build:
    runs-on: windows-latest

    steps:
    # 1. 拉取代码
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. 安装 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # 根据你的实际版本调整

    # 3. 安装项目依赖
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_streamlit.txt
        pip install pyinstaller pillow

    # 4. 使用 PyInstaller 打包 exe
    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --noconfirm `
          --onefile `
          --name StudentScoresApp `
          --collect-all streamlit `
          --add-data "app.py;." `
          --add-data "analyzer.py;." `
          --add-data "database.py;." `
          --add-data "styles.py;." `
          --add-data "config.py;." `
          --add-data "student_scores.db;." `
          --add-data "config;config" `
          --add-data "pages;pages" `
          --add-data "build_assets;build_assets" `
          --icon build_assets/icon.ico `
          run_app.py

    # 5. 上传打好的 exe 供下载
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: StudentScoresApp
        path: dist/*.exe
