name: Build EXE

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip uninstall -y streamlit || exit 0
        pip install streamlit pandas plotly openpyxl numpy pillow
        pip install pyinstaller

    - name: Build EXE with PyInstaller
      run: |
        $streamlitPath = python -c "import streamlit, os; print(os.path.dirname(streamlit.__file__))"
        pyinstaller --noconfirm --onefile --name StudentScoresApp `
          --collect-all streamlit `
          --add-data "app.py;." `
          --add-data "analyzer.py;." `
          --add-data "database.py;." `
          --add-data "styles.py;." `
          --add-data "config.py;." `
          --add-data "student_scores.db;." `
          --add-data "config;config" `
          --add-data "pages;pages" `
          --add-data "build_assets;build_assets" `
          --add-data "$streamlitPath\static;streamlit/static" `
          --add-data "$streamlitPath\frontend\build;streamlit/frontend/build" `
          --icon build_assets/icon.ico `
          run_app.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: StudentScoresApp
        path: dist/StudentScoresApp.exe
